# Generated by Django 5.1.3 on 2024-11-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("bio_waste", models.IntegerField(default=0)),
                ("glass", models.IntegerField(default=0)),
                ("plastic", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Storage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("bio_waste_capacity", models.IntegerField()),
                ("glass_capacity", models.IntegerField()),
                ("plastic_capacity", models.IntegerField()),
                ("bio_waste_current", models.IntegerField(default=0)),
                ("glass_current", models.IntegerField(default=0)),
                ("plastic_current", models.IntegerField(default=0)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
    ]
