# Generated by Django 5.1.3 on 2024-11-14 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eco", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storage",
            name="capacity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="storage",
            name="organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="eco.organization",
            ),
        ),
        migrations.AddField(
            model_name="storage",
            name="type",
            field=models.CharField(default="general", max_length=50),
        ),
    ]
